### ISSUE TITLE
panic-gui master incompatible with Taurus 4.0.1

### ISSUE THREAD

**Issue by sly74fr** [tango-controls/PANIC#1]
Hello,

I always get:
Traceback (most recent call last):
  File "/home/xtramgr/Dev/VirtualEnvs/AIT/bin/panic-gui", line 11, in <module>
    load_entry_point('panic==6.0', 'console_scripts', 'panic-gui')()
  File "/home/xtramgr/Dev/VirtualEnvs/AIT/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/xtramgr/Dev/VirtualEnvs/AIT/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2598, in load_entry_point
    return ep.load()
  File "/home/xtramgr/Dev/VirtualEnvs/AIT/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2258, in load
    return self.resolve()
  File "/home/xtramgr/Dev/VirtualEnvs/AIT/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2264, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/home/xtramgr/Dev/VirtualEnvs/AIT/local/lib/python2.7/site-packages/panic-6.0-py2.7.egg/panic/gui/**init**.py", line 2, in <module>
    from gui import *
  File "/home/xtramgr/Dev/VirtualEnvs/AIT/local/lib/python2.7/site-packages/panic-6.0-py2.7.egg/panic/gui/gui.py", line 11, in <module>
    from taurus.core import AttributeNameValidator
ImportError: cannot import name AttributeNameValidator

Any idea please ?
Regards

**Comment by sergirubio** [comment]
Hi. Taurus 4 is quite now to us also but in principle we should be compatible.

Tomorrow I'll try to reproduce this error and give you feedback,

Sergi

**Comment by sly74fr** [comment]
Thanx !

**Comment by sergirubio** [comment]
Hi, just an update

Panic-gui is actually compatible with Taurus 4 in some environments, but fails when mixing Tango7 and Tango9 devices in the control system behind.

Working on it, once solved I'll post a new update on the issue.

Sergi

**Comment by sergirubio** [comment]
Hi, this issue is solved in the 6.3 release
